### ISSUE TITLE
Mainchat.de 5.0.6

### ISSUE THREAD

**Issue by Sanji008** [netzhuffle/mainchat#8]
Hi, mainchat.de verwendet die Original 5.0.6, gibt's eine Möglichkeit das ihr die in die Branch "original" aufnehmt? Gruß

**Comment by ePfirsich** [comment]
> Hi, mainchat.de verwendet die Original 5.0.6, gibt's eine Möglichkeit das ihr die in die Branch "original" aufnehmt? Gruß

Besser spät als nie, aber was ist damit? :)
https://github.com/netzhuffle/mainchat/releases/tag/v5.0.6

**Comment by Sanji008** [comment]
Vielen Dank, ist aber leider die falsche Version. Auch hier steckt nur die 5.0.4 drinnen und die 5.0.6 bezieht sich auf die open MainChat.

Inzwischen verwendet mainchat.de die Version 8.0.8
